# Generated by Django 5.1 on 2026-02-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0003_pledge_supporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
